Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital

resources/views/index.blade.php
=> commit Alex_Villalba img div about issue #3

app/Http/Livewire/Admins/Patients.php
=> commit Marc_Galan undefined $password

resources/views/index.blade.php
=> #2 fix logo img title

resources/views/index.blade.php
=> #6 Contact section fixed

app/Http/Livewire/Admins/Beds.php
=> Beds component for render funcion must be checked #24

routes/test.php
=> commit Fix mistypo Suscribers #26 arnau poch

app/Http/Livewire/Admins/Appointments.php, resources/views/livewire/admins/appointment.blade.php, routes/web.php
Fix mistypo names in Appointment functionality
=> Fix mistypo names in Appointment functionality

app/Http/Livewire/Admins/Patients.php, app/Http/Livewire/Appointmentform.php, composer.lock, database/migrations/2021_05_06_051620_create_doctors_table.php, database/seeders/doctorSeeder.php, resources/views/livewire/admins/birthreport.blade.php, resources/views/livewire/appointmentform.blade.php
Now doctor's name come from employee's name column
=> Fix book apointment does not list doctors in drop down #9

app/Http/Livewire/Admins/Birthreport.php
=> Fixed no doctor listed when a birth reports wants to be added #39

app/Http/Controllers/PatientsController.php, database/seeders/DatabaseSeeder.php, database/seeders/PatientsTableSeeder.php, routes/api.php
=> create API to list all patients issue 34

app/Http/Controllers/PatientsController.php, app/Http/Controllers/RoomsController.php, routes/api.php
=> define a new api route with name rooms/available

app/Http/Controllers/DoctorsController.php, routes/api.php
=> create API to list all doctors issue #33

app/Http/Livewire/Admins/Hods.php, app/Models/doctor.php
#50 Fixed HOD form in admin/gods, they modify the eloquent consult
=> #50 fixed HOD form in admin/gods

composer.lock, resources/views/livewire/admins/patients.blade.php
=> #42 blood issue

app/Http/Controllers/BirthReportsController.php, routes/api.php
Done new API to retrieve data from birthreports table, all data gotten are retrieved in json format.
@Japoivvb 
Evidence:
Call from Postman
=> #37 done new API to retrive data from birth reports

app/Http/Controllers/DoctorsController.php, app/Models/doctor.php, routes/api.php
=> commit create api to list all doctors issue #33

README.md, database/seeders/appointmentSeeder.php
=> #128 Create Seeder Appointment

app/Http/Controllers/MedicinesController.php, routes/api.php
=> #98 create API to add a new medicine Alejandro Herrero Terrero

app/Http/Livewire/Admins/Bills.php, app/Models/bill.php, resources/views/livewire/admins/bills.blade.php
Rename fro Bill's to Bills
Bill amount is not defined in database table
Payed field return paid or not paid
=> Fix bills form and data definition #40

resources/views/livewire/admins/rooms.blade.php
=> Room type form does not have closed values list #69 Arnau Poch

resources/views/livewire/admins/rooms.blade.php
=> type and available are not showing  #68

app/Http/Controllers/BillsController.php, app/Http/Livewire/Admins/Bills.php, resources/views/livewire/admins/bills.blade.php
You can fill the checkbox or not. If you do it, your status become to payed. On contrary, your status become to unpaid.
=> Updated status. #40

database/seeders/DatabaseSeeder.php, database/seeders/subscriberSeeder.php
=> created subscriberSeeder commit

app/Models/beds.php, resources/views/livewire/admins/beds.blade.php
=> #15 issue admin/beds resolved

app/Http/Controllers/AnalyzeController.php, app/Http/Livewire/Patients/SymptomCheck.php, public/js/modernizer.js, resources/views/livewire/patients/symptom_check.blade.php, routes/web.php
FrontEnd (formulario) para poner síntomas y analizar. He cambiado cosas en el AnalyzeController y en SymptomCheck.php y symptom_check.blade.php
=> Update Symptom Check
